<a href="https://colab.research.google.com/github/souhirbenamor/EPF/blob/main/LEAR_Easy_recalibration_Bridging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
!pip install gitpython

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 181 kB 5.2 MB/s 
     |████████████████████████████████| 63 kB 1.4 MB/s 


In [ ]:
import os
from git.repo.base import Repo
Repo.clone_from("https://github.com/jeslago/epftoolbox", "epftoolbox")

<git.repo.base.Repo '/content/epftoolbox/.git'>

In [ ]:
cd epftoolbox

/content/epftoolbox


In [ ]:
#from epftoolbox.data import read_data
#df_train, df_test = read_data(path='.', dataset='EPF_data', begin_test_date='28-12-2015',end_test_date='31-12-2016')

In [ ]:
#df_train

Price  Exogenous 1  Exogenous 2
Date                                                
2011-01-09 00:00:00  18.29        40242       8280.0
2011-01-09 01:00:00  16.04        39159       8413.0
2011-01-09 02:00:00  14.60        38825       8502.0
2011-01-09 03:00:00  14.95        38969       8669.0
2011-01-09 04:00:00  14.50        39093       8849.0
...                    ...          ...          ...
2015-12-27 19:00:00  35.69        65864      23686.0
2015-12-27 20:00:00  35.09        62098      23236.0
2015-12-27 21:00:00  32.95        59293      22718.0
2015-12-27 22:00:00  27.22        55256      22390.0
2015-12-27 23:00:00  26.56        50849      22086.0

[43536 rows x 3 columns]

In [ ]:
#df_test

Price  Exogenous 1  Exogenous 2
Date                                                
2015-12-28 00:00:00  25.95        47965     21729.00
2015-12-28 01:00:00  23.30        47262     21491.00
2015-12-28 02:00:00  19.01        47679     21549.00
2015-12-28 03:00:00  24.59        48870     22197.00
2015-12-28 04:00:00  25.03        52302     23355.00
...                    ...          ...          ...
2016-12-31 19:00:00  40.25        59627     19911.50
2016-12-31 20:00:00  33.15        56876     20879.50
2016-12-31 21:00:00  30.39        54637     21307.75
2016-12-31 22:00:00  25.85        50930     21778.25
2016-12-31 23:00:00   1.59        45437     27305.00

[8880 rows x 3 columns]

In [ ]:
#from epftoolbox.data import DataScaler
#Xtrain = df_train.values
#Xtest = df_train.values
#scaler = DataScaler('Norm')
#Xtrain_scaled = scaler.fit_transform(Xtrain)
#Xtest_scaled = scaler.transform(Xtest)
#Xtrain_inverse = scaler.inverse_transform(Xtrain_scaled)
#Xtest_inverse = scaler.inverse_transform(Xtest_scaled)
#Xtrain[:3,:]

array([[1.8290e+01, 4.0242e+04, 8.2800e+03],
       [1.6040e+01, 3.9159e+04, 8.4130e+03],
       [1.4600e+01, 3.8825e+04, 8.5020e+03]])

In [ ]:
#Xtrain_scaled[:3,:]

array([[0.50536426, 0.22711934, 0.13419524],
       [0.49770103, 0.20483539, 0.13649405],
       [0.49279657, 0.19796296, 0.13803236]])

In [ ]:
#Xtrain_inverse[:3,:]

array([[1.8290e+01, 4.0242e+04, 8.2800e+03],
       [1.6040e+01, 3.9159e+04, 8.4130e+03],
       [1.4600e+01, 3.8825e+04, 8.5020e+03]])

In [ ]:
 #Xtest[:3,:]

array([[1.8290e+01, 4.0242e+04, 8.2800e+03],
       [1.6040e+01, 3.9159e+04, 8.4130e+03],
       [1.4600e+01, 3.8825e+04, 8.5020e+03]])

In [ ]:
#Xtest_scaled[:3,:]

array([[0.50536426, 0.22711934, 0.13419524],
       [0.49770103, 0.20483539, 0.13649405],
       [0.49279657, 0.19796296, 0.13803236]])

In [ ]:
#Xtest_inverse[:3,:]

array([[1.8290e+01, 4.0242e+04, 8.2800e+03],
       [1.6040e+01, 3.9159e+04, 8.4130e+03],
       [1.4600e+01, 3.8825e+04, 8.5020e+03]])

In [ ]:
#from epftoolbox.data import scaling
#Xtrain = df_train.values
#Xtest = df_train.values
#[Xtrain_scaled, Xtest_scaled], scaler = scaling([Xtrain,Xtest],'Norm')
#Xtrain[:3,:]


array([[1.8290e+01, 4.0242e+04, 8.2800e+03],
       [1.6040e+01, 3.9159e+04, 8.4130e+03],
       [1.4600e+01, 3.8825e+04, 8.5020e+03]])

In [ ]:
#Xtrain_scaled[:3,:]

array([[0.50536426, 0.22711934, 0.13419524],
       [0.49770103, 0.20483539, 0.13649405],
       [0.49279657, 0.19796296, 0.13803236]])

In [ ]:
#Xtest[:3,:]

array([[1.8290e+01, 4.0242e+04, 8.2800e+03],
       [1.6040e+01, 3.9159e+04, 8.4130e+03],
       [1.4600e+01, 3.8825e+04, 8.5020e+03]])

In [ ]:
#Xtest_scaled[:3,:]

array([[0.50536426, 0.22711934, 0.13419524],
       [0.49770103, 0.20483539, 0.13649405],
       [0.49279657, 0.19796296, 0.13803236]])

In [ ]:
#type(scaler)

epftoolbox.data._wrangling.DataScaler

In [ ]:
import pandas as pd
import numpy as np
import argparse
import os

from epftoolbox.data import read_data
from epftoolbox.evaluation import MAE, sMAPE
from epftoolbox.models import LEAR

In [ ]:
from epftoolbox.models import evaluate_lear_in_test_dataset
import os

# Market under study. If it not one of the standard ones, the file name
# has to be provided, where the file has to be a csv file
dataset = 'EPF'



In [ ]:
# Number of years (a year is 364 days) in the test dataset.
years_test = 2.0195

# Number of days used in the training dataset for recalibration
calibration_window = 364 * 4

# Optional parameters for selecting the test dataset, if either of them is not provided, 
# the test dataset is built using the years_test parameter. They should either be one of
# the date formats existing in python or a string with the following format
# "%d/%m/%Y %H:%M"
begin_test_date = '05/01/2015'
end_test_date = '08/01/2017'



In [ ]:
path_datasets_folder = os.path.join('.', 'datasets')
path_recalibration_folder = os.path.join('.', 'experimental_files')


In [ ]:
dataset

'EPF'

In [ ]:
EPF_1=pd.read_csv('/content/EPF_data 2.csv')
EPF_1.reset_index(inplace=True)
EPF_1["Date"] = pd.to_datetime(EPF_1["Date"])
EPF_1 = EPF_1.set_index('Date')
del EPF_1['index']
EPF_1.head()
print(EPF_1)


                     price day ahead real  Load Forecast  PV+Wind Forecast  \
Date                                                                         
2011-01-09 00:00:00                 18.29          40242            8280.0   
2011-01-09 01:00:00                 16.04          39159            8413.0   
2011-01-09 02:00:00                 14.60          38825            8502.0   
2011-01-09 03:00:00                 14.95          38969            8669.0   
2011-01-09 04:00:00                 14.50          39093            8849.0   
...                                   ...            ...               ...   
2017-01-08 19:00:00                 56.70          49516            8053.5   
2017-01-08 20:00:00                 52.44          47748            7456.5   
2017-01-08 21:00:00                 51.86          47762            6902.5   
2017-01-08 22:00:00                 52.26          46223            6395.0   
2017-01-08 23:00:00                 50.87          43521        

In [ ]:
EPF_1.to_csv('/content/epftoolbox/datasets/EPF.csv')

In [ ]:
    
evaluate_lear_in_test_dataset(path_recalibration_folder=path_recalibration_folder, 
                             path_datasets_folder=path_datasets_folder, dataset=dataset, years_test=years_test, 
                             calibration_window=calibration_window, begin_test_date=begin_test_date, 
                             end_test_date=end_test_date)


Test datasets: 2015-01-05 00:00:00 - 2017-01-08 23:00:00
2015-01-05 - sMAPE: 7.96%  |  MAE: 4.253
2015-01-06 - sMAPE: 16.76%  |  MAE: 6.319
2015-01-07 - sMAPE: 35.25%  |  MAE: 9.581
2015-01-08 - sMAPE: 30.26%  |  MAE: 9.390
2015-01-09 - sMAPE: 62.41%  |  MAE: 15.061
2015-01-10 - sMAPE: 60.69%  |  MAE: 15.381
2015-01-11 - sMAPE: 53.85%  |  MAE: 14.215
2015-01-12 - sMAPE: 49.59%  |  MAE: 13.556
2015-01-13 - sMAPE: 45.81%  |  MAE: 12.781
2015-01-14 - sMAPE: 42.39%  |  MAE: 12.108
2015-01-15 - sMAPE: 40.17%  |  MAE: 11.524
2015-01-16 - sMAPE: 38.24%  |  MAE: 11.015
2015-01-17 - sMAPE: 37.48%  |  MAE: 10.823
2015-01-18 - sMAPE: 35.60%  |  MAE: 10.711
2015-01-19 - sMAPE: 34.23%  |  MAE: 10.451
2015-01-20 - sMAPE: 32.63%  |  MAE: 10.003
2015-01-21 - sMAPE: 35.79%  |  MAE: 10.309
2015-01-22 - sMAPE: 36.63%  |  MAE: 10.365
2015-01-23 - sMAPE: 35.26%  |  MAE: 10.069
2015-01-24 - sMAPE: 34.05%  |  MAE: 9.807
2015-01-25 - sMAPE: 32.88%  |  MAE: 9.537
2015-01-26 - sMAPE: 32.10%  |  MAE: 9.614
2015-

In [ ]:
#Download available forecast
import pandas as pd
import numpy as np
forecast = pd.read_csv('/content/epftoolbox/experimental_files/LEAR_forecast_datEPF_YT2.0195_CW1456.csv')
forecast.reset_index(inplace=True)
forecast['Date'] = pd.to_datetime(forecast['Date'])
forecast = forecast.set_index('Date')
forecast.head()

index         h0         h1         h2         h3         h4  \
Date                                                                       
2015-01-05      0  46.568490  42.995123  40.284090  41.281372  42.769975   
2015-01-06      1  49.232449  45.891539  42.221738  39.319878  39.635293   
2015-01-07      2  10.318326   8.978287   8.983570  10.914104  13.664986   
2015-01-08      3  46.276746  46.118965  40.293061  39.335919  40.410901   
2015-01-09      4  24.809524  23.955762  23.313370  25.723276  25.426540   

                   h5         h6         h7         h8  ...        h14  \
Date                                                    ...              
2015-01-05  48.631243  59.738275  68.982391  70.665136  ...  65.956961   
2015-01-06  40.613125  46.673612  52.619035  54.346655  ...  37.060859   
2015-01-07  11.588890  19.540403  24.801572  27.033876  ...  32.183776   
2015-01-08  44.632480  58.655376  67.716193  75.410262  ...  67.183412   
2015-01-09  27.976011  30.580189  32.744905  31.537329  ...  28.952147   

                  h15        h16        h17        h18        h19        h20  \
Date                                                                           
2015-01-05  68.530264  70.262717  64.592610  68.015008  62.081806  53.893415   
2015-01-06  39.751742  44.693803  44.058805  42.892432  39.110551  35.908827   
2015-01-07  37.500603  46.487046  49.063200  47.820410  43.998154  40.302034   
2015-01-08  62.647594  61.068341  56.340652  49.242477  44.968372  39.227561   
2015-01-09  34.815087  42.122917  45.336609  42.670484  38.020318  35.055658   

                  h21        h22        h23  
Date                                         
2015-01-05  54.354808  45.187559  40.988686  
2015-01-06  34.322179  27.511253  25.160083  
2015-01-07  40.694414  34.887822  32.419050  
2015-01-08  37.784033  34.687685  30.667673  
2015-01-09  31.582450  25.311587  22.315885  

[5 rows x 25 columns]

In [ ]:
forecast=forecast.iloc[:, 2:] 
df=forecast.stack()
df.to_excel("forecast_LEAR_2.xlsx", header=True)
print(df)

Date           
2015-01-05  h1     42.995123
            h2     40.284090
            h3     41.281372
            h4     42.769975
            h5     48.631243
                     ...    
2017-01-08  h19    54.935606
            h20    52.303738
            h21    54.075753
            h22    51.737942
            h23    47.410246
Length: 16905, dtype: float64


In [ ]:
df=forecast.stack()

In [ ]:
df

Date           
2015-01-05  h1     42.995123
            h2     40.284090
            h3     41.281372
            h4     42.769975
            h5     48.631243
                     ...    
2017-01-08  h19    54.935606
            h20    52.303738
            h21    54.075753
            h22    51.737942
            h23    47.410246
Length: 16905, dtype: float64

In [ ]:

df.to_excel("forecast_LEAR_2.xlsx", header=True)