<a href="https://colab.research.google.com/github/souhirbenamor/EPF/blob/main/LEAR_Easy_recalibration_Bridging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
!pip install gitpython

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 182 kB 5.1 MB/s 
     |████████████████████████████████| 63 kB 1.7 MB/s 


In [ ]:
import os
from git.repo.base import Repo
Repo.clone_from("https://github.com/jeslago/epftoolbox", "epftoolbox")

<git.repo.base.Repo '/content/epftoolbox/.git'>

In [ ]:
cd epftoolbox

/content/epftoolbox


In [ ]:
#from epftoolbox.data import read_data
#df_train, df_test = read_data(path='.', dataset='EPF_data', begin_test_date='28-12-2015',end_test_date='31-12-2016')

In [ ]:
#df_train

Price  Exogenous 1  Exogenous 2
Date                                                
2011-01-09 00:00:00  18.29        40242       8280.0
2011-01-09 01:00:00  16.04        39159       8413.0
2011-01-09 02:00:00  14.60        38825       8502.0
2011-01-09 03:00:00  14.95        38969       8669.0
2011-01-09 04:00:00  14.50        39093       8849.0
...                    ...          ...          ...
2015-12-27 19:00:00  35.69        65864      23686.0
2015-12-27 20:00:00  35.09        62098      23236.0
2015-12-27 21:00:00  32.95        59293      22718.0
2015-12-27 22:00:00  27.22        55256      22390.0
2015-12-27 23:00:00  26.56        50849      22086.0

[43536 rows x 3 columns]

In [ ]:
#df_test

Price  Exogenous 1  Exogenous 2
Date                                                
2015-12-28 00:00:00  25.95        47965     21729.00
2015-12-28 01:00:00  23.30        47262     21491.00
2015-12-28 02:00:00  19.01        47679     21549.00
2015-12-28 03:00:00  24.59        48870     22197.00
2015-12-28 04:00:00  25.03        52302     23355.00
...                    ...          ...          ...
2016-12-31 19:00:00  40.25        59627     19911.50
2016-12-31 20:00:00  33.15        56876     20879.50
2016-12-31 21:00:00  30.39        54637     21307.75
2016-12-31 22:00:00  25.85        50930     21778.25
2016-12-31 23:00:00   1.59        45437     27305.00

[8880 rows x 3 columns]

In [ ]:
#from epftoolbox.data import DataScaler
#Xtrain = df_train.values
#Xtest = df_train.values
#scaler = DataScaler('Norm')
#Xtrain_scaled = scaler.fit_transform(Xtrain)
#Xtest_scaled = scaler.transform(Xtest)
#Xtrain_inverse = scaler.inverse_transform(Xtrain_scaled)
#Xtest_inverse = scaler.inverse_transform(Xtest_scaled)
#Xtrain[:3,:]

array([[1.8290e+01, 4.0242e+04, 8.2800e+03],
       [1.6040e+01, 3.9159e+04, 8.4130e+03],
       [1.4600e+01, 3.8825e+04, 8.5020e+03]])

In [ ]:
#Xtrain_scaled[:3,:]

array([[0.50536426, 0.22711934, 0.13419524],
       [0.49770103, 0.20483539, 0.13649405],
       [0.49279657, 0.19796296, 0.13803236]])

In [ ]:
#Xtrain_inverse[:3,:]

array([[1.8290e+01, 4.0242e+04, 8.2800e+03],
       [1.6040e+01, 3.9159e+04, 8.4130e+03],
       [1.4600e+01, 3.8825e+04, 8.5020e+03]])

In [ ]:
 #Xtest[:3,:]

array([[1.8290e+01, 4.0242e+04, 8.2800e+03],
       [1.6040e+01, 3.9159e+04, 8.4130e+03],
       [1.4600e+01, 3.8825e+04, 8.5020e+03]])

In [ ]:
#Xtest_scaled[:3,:]

array([[0.50536426, 0.22711934, 0.13419524],
       [0.49770103, 0.20483539, 0.13649405],
       [0.49279657, 0.19796296, 0.13803236]])

In [ ]:
#Xtest_inverse[:3,:]

array([[1.8290e+01, 4.0242e+04, 8.2800e+03],
       [1.6040e+01, 3.9159e+04, 8.4130e+03],
       [1.4600e+01, 3.8825e+04, 8.5020e+03]])

In [ ]:
#from epftoolbox.data import scaling
#Xtrain = df_train.values
#Xtest = df_train.values
#[Xtrain_scaled, Xtest_scaled], scaler = scaling([Xtrain,Xtest],'Norm')
#Xtrain[:3,:]


array([[1.8290e+01, 4.0242e+04, 8.2800e+03],
       [1.6040e+01, 3.9159e+04, 8.4130e+03],
       [1.4600e+01, 3.8825e+04, 8.5020e+03]])

In [ ]:
#Xtrain_scaled[:3,:]

array([[0.50536426, 0.22711934, 0.13419524],
       [0.49770103, 0.20483539, 0.13649405],
       [0.49279657, 0.19796296, 0.13803236]])

In [ ]:
#Xtest[:3,:]

array([[1.8290e+01, 4.0242e+04, 8.2800e+03],
       [1.6040e+01, 3.9159e+04, 8.4130e+03],
       [1.4600e+01, 3.8825e+04, 8.5020e+03]])

In [ ]:
#Xtest_scaled[:3,:]

array([[0.50536426, 0.22711934, 0.13419524],
       [0.49770103, 0.20483539, 0.13649405],
       [0.49279657, 0.19796296, 0.13803236]])

In [ ]:
#type(scaler)

epftoolbox.data._wrangling.DataScaler

In [ ]:
import pandas as pd
import numpy as np
import argparse
import os

from epftoolbox.data import read_data
from epftoolbox.evaluation import MAE, sMAPE
from epftoolbox.models import LEAR

In [ ]:
from epftoolbox.models import evaluate_lear_in_test_dataset
import os

# Market under study. If it not one of the standard ones, the file name
# has to be provided, where the file has to be a csv file
dataset = 'EPF_data_FUND'



In [ ]:
# Number of years (a year is 364 days) in the test dataset.
years_test = 2.0195

# Number of days used in the training dataset for recalibration
calibration_window = 364 * 4

# Optional parameters for selecting the test dataset, if either of them is not provided, 
# the test dataset is built using the years_test parameter. They should either be one of
# the date formats existing in python or a string with the following format
# "%d/%m/%Y %H:%M"
begin_test_date = '05/01/2015'
end_test_date = '08/01/2017'



In [ ]:
path_datasets_folder = os.path.join('.', 'datasets')
path_recalibration_folder = os.path.join('.', 'experimental_files')


In [ ]:
dataset

'EPF_data_FUND'

In [ ]:
EPF_1=pd.read_excel('/content/EPF_data_FUND.xlsx')
EPF_1.reset_index(inplace=True)
EPF_1["Date"] = pd.to_datetime(EPF_1["Date"])
EPF_1 = EPF_1.set_index('Date')
del EPF_1['index']
EPF_1.head()
print(EPF_1)


In [ ]:
EPF_1.to_csv('/content/EPF_data_FUND.csv')

In [ ]:
    
evaluate_lear_in_test_dataset(path_recalibration_folder=path_recalibration_folder, 
                             path_datasets_folder=path_datasets_folder, dataset=dataset, years_test=years_test, 
                             calibration_window=calibration_window, begin_test_date=begin_test_date, 
                             end_test_date=end_test_date)


Test datasets: 2015-01-05 00:00:00 - 2017-01-08 23:00:00
2015-01-05 - sMAPE: 8.71%  |  MAE: 4.604
2015-01-06 - sMAPE: 15.83%  |  MAE: 5.926
2015-01-07 - sMAPE: 33.31%  |  MAE: 8.077
2015-01-08 - sMAPE: 29.00%  |  MAE: 8.461
2015-01-09 - sMAPE: 61.19%  |  MAE: 13.208
2015-01-10 - sMAPE: 59.56%  |  MAE: 13.717
2015-01-11 - sMAPE: 52.84%  |  MAE: 12.684
2015-01-12 - sMAPE: 49.35%  |  MAE: 12.462
2015-01-13 - sMAPE: 45.93%  |  MAE: 11.952
2015-01-14 - sMAPE: 42.49%  |  MAE: 11.404
2015-01-15 - sMAPE: 40.27%  |  MAE: 10.913
2015-01-16 - sMAPE: 38.07%  |  MAE: 10.360
2015-01-17 - sMAPE: 36.89%  |  MAE: 10.066
2015-01-18 - sMAPE: 34.74%  |  MAE: 9.714
2015-01-19 - sMAPE: 33.29%  |  MAE: 9.459
2015-01-20 - sMAPE: 31.78%  |  MAE: 9.088
2015-01-21 - sMAPE: 34.58%  |  MAE: 9.192
2015-01-22 - sMAPE: 34.33%  |  MAE: 9.114
2015-01-23 - sMAPE: 33.09%  |  MAE: 8.881
2015-01-24 - sMAPE: 32.18%  |  MAE: 8.757
2015-01-25 - sMAPE: 31.23%  |  MAE: 8.592
2015-01-26 - sMAPE: 30.55%  |  MAE: 8.739
2015-01-27 

In [ ]:
#Download available forecast
import pandas as pd
import numpy as np
forecast = pd.read_csv('/content/DNN_forecast_nl2_datEPF_data S3_YT2_SFH1_CW4_1.csv')
forecast.reset_index(inplace=True)
forecast['Date'] = pd.to_datetime(forecast['Date'])
forecast = forecast.set_index('Date')
print(forecast)

            index         h0         h1         h2         h3         h4  \
Date                                                                       
2015-01-05      0  51.465088  51.125839  50.888016  50.548141  51.177063   
2015-01-06      1  47.233803  46.335350  44.912575  44.852081  46.775047   
2015-01-07      2   3.061676   2.166248  -0.065741   0.792267  -3.932011   
2015-01-08      3  43.318512  41.074856  40.320946  40.603546  41.145702   
2015-01-09      4  18.564064  16.300333  11.418878  10.201815   4.284416   
...           ...        ...        ...        ...        ...        ...   
2017-01-04    730 -25.733772 -28.228739 -27.849907 -26.055752 -20.752888   
2017-01-05    731   6.886381   6.129295   7.185358   9.229809  19.593575   
2017-01-06    732  38.416862  37.317528  35.642723  35.277199  37.911041   
2017-01-07    733  35.417385  35.635826  34.380829  34.429054  36.965607   
2017-01-08    734  36.474545  36.181095  35.175919  35.388645  36.699722   

           

In [ ]:
forecast=forecast.iloc[:, 1:] 
df=forecast.stack()
df.to_excel("forecast_LEAR_2.xlsx", header=True)
print(df)

Date           
2015-01-05  h0     51.465088
            h1     51.125839
            h2     50.888016
            h3     50.548141
            h4     51.177063
                     ...    
2017-01-08  h19    55.626308
            h20    50.832794
            h21    47.794525
            h22    44.460091
            h23    43.684372
Length: 17640, dtype: float64


In [ ]:
df

Date           
2015-01-05  h0     51.465088
            h1     51.125839
            h2     50.888016
            h3     50.548141
            h4     51.177063
                     ...    
2017-01-08  h19    55.626308
            h20    50.832794
            h21    47.794525
            h22    44.460091
            h23    43.684372
Length: 17640, dtype: float64

In [ ]:

df.to_excel("forecast_LEAR_2.xlsx", header=True)