<a href="https://colab.research.google.com/github/souhirbenamor/EPF/blob/main/Recursive_feature_Elimination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/MachineLearnia/Python-Machine-Learning/blob/master/23%20-%20Sklearn%20Feature%20Selection.**ipynb**

In [180]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [181]:
df = pd.read_csv('/content/NP_exo-2.csv')

#df = df.set_index("Date") # define Date  as index

df.shape

(52416, 7)

In [189]:
X=df.iloc[:, 1:7]
y=df.iloc[:, 0]

In [191]:
feature_names = list(X.columns.values)

# 1. Variance Threshold

In [192]:
from sklearn.feature_selection import VarianceThreshold

In [193]:
X.var(axis=0)

 Grid load forecast         7.550860e+07
 Wind power forecast        1.291355e+06
NP Consumption              7.457011e+07
NP Consumption prognosis    7.578419e+07
NP Production               8.516992e+07
NP Production prognosis     8.288054e+07
dtype: float64

In [194]:
selector = VarianceThreshold(threshold=0.2)
selector.fit(X)

VarianceThreshold(threshold=0.2)

In [195]:
selector.get_support()

array([ True,  True,  True,  True,  True,  True])

In [196]:
np.array(feature_names)[selector.get_support()]

array([' Grid load forecast', ' Wind power forecast', 'NP Consumption',
       'NP Consumption prognosis', 'NP Production',
       'NP Production prognosis'], dtype='<U24')

In [197]:
selector.variances_

array([75507159.01411188,  1291330.5030808 , 74568689.60528776,
       75782744.20445755, 85168297.58204749, 82878960.11765087])

# 2. SelectKBest

In [198]:
from sklearn.feature_selection import SelectKBest, chi2, f_classif

In [200]:
y=y.astype('int')

In [201]:
chi2(X, y)

(array([13658634.91708614,  1612385.44463438, 10541824.11032791,
        10386210.4616281 ,  8173717.62366025,  8357949.32045664]),
 array([0., 0., 0., 0., 0., 0.]))

In [203]:
selector = SelectKBest(f_classif, k=2)
selector.fit(X, y)
selector.scores_

array([89.69392727, 18.53645475, 67.25220705, 65.12056606, 44.76303966,
       46.40652263])

In [205]:
np.array(feature_names)[selector.get_support()]

array([' Grid load forecast', 'NP Consumption'], dtype='<U24')

# 3. Recursive feature Elimination

In [206]:
from sklearn.feature_selection import RFECV
from sklearn.linear_model import SGDClassifier

In [207]:
selector = RFECV(SGDClassifier(random_state=0), step=1, min_features_to_select=2, cv=5)
selector.fit(X, y)
print(selector.ranking_)
print(selector.grid_scores_)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,


[1 1 1 3 1 2]
[[0.01735979 0.02012783 0.02995326 0.00524659 0.05141658]
 [0.04912247 0.02699609 0.02022322 0.04922255 0.03348278]
 [0.04912247 0.00953925 0.02871315 0.05170276 0.05141658]
 [0.01182755 0.01631212 0.0281408  0.05418296 0.03500906]
 [0.04807325 0.01631212 0.02356196 0.02365735 0.05122579]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:103: FutureWarning: The `grid_scores_` attribute is deprecated in version 1.0 in favor of `cv_results_` and will be removed in version 1.2.
  warnings.warn(msg, category=FutureWarning)


In [208]:
np.array(feature_names)[selector.get_support()]

array([' Grid load forecast', ' Wind power forecast', 'NP Consumption',
       'NP Production'], dtype='<U24')

# 4. SelectFromModel

In [209]:
from sklearn.feature_selection import SelectFromModel

In [210]:
selector = SelectFromModel(SGDClassifier(random_state=0), threshold='mean')
selector.fit(X, y)
selector.estimator_.coef_

array([[-6.41577226e+02,  3.23241364e+03,  4.61244528e+02,
         5.51824663e+02, -7.30866619e+02, -5.42373978e+02],
       [-1.18657984e+03,  4.87010408e+03, -1.70420374e+02,
         3.02871271e+02,  8.12744749e+02, -6.71632589e+02],
       [-7.29733186e+02,  3.97889658e+03, -7.36732457e+02,
        -2.25153242e+02,  7.53590138e+02,  1.67251646e+00],
       [-6.05361585e+02,  3.68191691e+03, -1.56851166e+03,
        -5.51464969e+02,  1.13595217e+03,  1.05917579e+03],
       [-3.80206441e+02,  2.38120129e+03, -1.85502300e+03,
        -5.80423628e+02,  1.19477551e+03,  9.09869068e+02],
       [-5.01081438e+02,  2.24963742e+03, -2.26804218e+03,
        -5.24005743e+02,  1.12484165e+03,  1.28314964e+03],
       [-2.42838532e+02,  1.49309485e+03, -1.42391703e+03,
        -4.11503283e+02,  8.58305354e+02,  7.02131426e+02],
       [-2.15320183e+02,  9.69158291e+02, -1.11973295e+03,
        -3.09611596e+02,  7.98979464e+02,  4.99555046e+02],
       [-2.00065536e+02,  9.83870253e+02, -1.231

In [211]:
np.array(feature_names)[selector.get_support()]

array([' Wind power forecast'], dtype='<U24')